# Generated by Django 5.2.7 on 2025-11-01 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='umkm',
            name='category',
            field=models.CharField(choices=[('food', 'Makanan'), ('drink', 'Minuman'), ('service', 'Jasa')], default='food', max_length=32),
        ),
        migrations.CreateModel(
            name='UMKMImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='umkm_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('umkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='api.umkm')),
            ],
        ),
    ]
