# Generated by Django 5.2.7 on 2025-11-01 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_umkm_category_umkmimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='umkmimage',
            options={'default_permissions': ()},
        ),
    ]
